### ISSUE TITLE
InvalidArgument with auto-detect

### ISSUE THREAD

**Issue by Illthani** [w-e-w/sd-webui-nudenet-nsfw-censor#20] opened 2024-08-17 07:10 UTC
Whenever I try to generate with auto-detect on I get the following error:

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices index: 1 Got: 4 Expected: 3 Please fix either the inputs/outputs or the model.
Time taken: 2.4 sec.

A: 1.86 GB, R: 1.91 GB, Sys: 3.3/6 GB (55.6%)

Am I doing something wrong? First time using all of these tools.

All the settings are on default, all I do is check the NSFW Censor box from the extras tab...

**Comment by w-e-w** [comment] 2024-08-17 07:13
post the entire error logs from the console
the error message from the UI alone is practically useless

also upload sysinfo found under webnUI settings sysinfo section

**Comment by w-e-w** [comment] 2024-08-17 07:35
- convert image to RGB mode https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/commit/aa3850c13430d45bd679bb9ed291c01adf2c11ab

the issue is caused by the model got an input of RBGA image instead of RGB, hence the error `Got: 4 Expected: 3`
I only got the issue when using Extras tab because Extras tab sometimes can have RGBA images
however I am not sure how this this issue can happened during an SD image gen as SD produce RGB images
so I'm guessing you also have an additional extension that combined with my extension didn't properly converted the image to RGB causes this issue

Either way it should be fixed now, update to the update to the latest version

**Closed by w-e-w** 2024-08-17 07:35 UTC
